import { jsPDF } from "jspdf";
import { ResearchReport } from "@/types/agent";

export async function generatePDF(report: ResearchReport): Promise<void> {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // Helper function to add text with word wrap
  const addText = (text: string, fontSize: number, isBold = false, color = '#1a1a2e') => {
    doc.setFontSize(fontSize);
    doc.setFont('helvetica', isBold ? 'bold' : 'normal');
    doc.setTextColor(color);
    const lines = doc.splitTextToSize(text, contentWidth);
    
    // Check if we need a new page
    const lineHeight = fontSize * 0.5;
    if (y + lines.length * lineHeight > doc.internal.pageSize.getHeight() - margin) {
      doc.addPage();
      y = margin;
    }
    
    doc.text(lines, margin, y);
    y += lines.length * lineHeight + 5;
  };

  // Header
  doc.setFillColor(26, 26, 46);
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor('#14b8a6');
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('PharmAI Research Report', margin, 25);

  y = 50;

  // Title
  addText(report.title, 18, true);
  y += 5;

  // Metadata
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  addText(`Generated: ${report.generatedAt.toLocaleString()}`, 10, false, '#666666');
  addText(`Query: ${report.query}`, 10, false, '#666666');
  y += 10;

  // Executive Summary
  doc.setFillColor(240, 253, 250);
  doc.roundedRect(margin, y, contentWidth, 50, 3, 3, 'F');
  y += 8;
  
  addText('Executive Summary', 14, true, '#14b8a6');
  addText(report.executiveSummary, 10, false, '#333333');
  y += 20;

  // Key Findings
  addText('Key Findings', 14, true);
  y += 5;

  report.findings.keyFindings.forEach((finding, index) => {
    // Check for page break
    if (y > doc.internal.pageSize.getHeight() - 60) {
      doc.addPage();
      y = margin;
    }

    // Finding box
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(margin, y, contentWidth, 35, 2, 2, 'F');
    
    // Confidence badge
    const badgeColor = finding.confidence === 'high' ? '#10b981' : 
                       finding.confidence === 'medium' ? '#f59e0b' : '#6b7280';
    doc.setFillColor(badgeColor);
    doc.roundedRect(pageWidth - margin - 30, y + 5, 25, 8, 2, 2, 'F');
    doc.setTextColor('#ffffff');
    doc.setFontSize(8);
    doc.text(finding.confidence.toUpperCase(), pageWidth - margin - 28, y + 10);

    y += 8;
    addText(`${index + 1}. ${finding.title}`, 11, true, '#1a1a2e');
    addText(finding.description, 9, false, '#4a5568');
    addText(`Source: ${finding.source}`, 8, false, '#718096');
    y += 10;
  });

  // Strategic Recommendations
  if (report.findings.recommendations.length > 0) {
    if (y > doc.internal.pageSize.getHeight() - 80) {
      doc.addPage();
      y = margin;
    }

    addText('Strategic Recommendations', 14, true);
    y += 5;

    report.findings.recommendations.forEach((rec, index) => {
      addText(`${index + 1}. ${rec}`, 10, false, '#333333');
    });
  }

  // Data Sources
  if (report.findings.dataSources.length > 0) {
    y += 10;
    addText('Data Sources', 12, true, '#666666');
    const sources = report.findings.dataSources.map(s => s.name).join(' • ');
    addText(sources, 9, false, '#888888');
  }

  // Footer
  const pageCount = doc.internal.pages.length - 1;
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor('#999999');
    doc.text(
      `Page ${i} of ${pageCount} | Generated by PharmAI Research Assistant`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }

  // Save the PDF
  const fileName = `pharmai-report-${Date.now()}.pdf`;
  doc.save(fileName);
}
